# Generated by Django 2.1.4 on 2018-12-20 18:40

from django.db import migrations, models
import django.db.models.deletion
import emacs_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('emacs_api', '0002_auto_20181219_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.FileField(upload_to=emacs_api.models.user_directory_path)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emacs_api.Document')),
            ],
        ),
    ]
