# Generated by Django 2.1.4 on 2018-12-20 18:49

from django.db import migrations, models
import emacs_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('emacs_api', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='document',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.FileField(default=[], upload_to=emacs_api.models.user_directory_path),
            preserve_default=False,
        ),
    ]
