# Generated by Django 2.1.4 on 2018-12-20 18:57

from django.db import migrations, models
import django.db.models.deletion
import emacs_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('emacs_api', '0004_auto_20181220_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.FileField(upload_to=emacs_api.models.user_directory_path)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='document',
            name='image',
        ),
        migrations.AddField(
            model_name='document',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emacs_api.Figure'),
        ),
    ]
