# Generated by Django 2.1.4 on 2018-12-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emacs_api', '0005_auto_20181220_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='images',
        ),
        migrations.AddField(
            model_name='document',
            name='images',
            field=models.ManyToManyField(null=True, to='emacs_api.Figure'),
        ),
    ]
