# Generated by Django 2.1.4 on 2018-12-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emacs_api', '0006_auto_20181220_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='images',
            field=models.ManyToManyField(blank=True, to='emacs_api.Figure'),
        ),
    ]
