- name: Deploy Django site
  hosts: nova-print
  remote_user: root
  tasks:
  - name: Upload nova_print django project sources
    copy:
      src: ~/code/nova-print/nova_print
      dest: ~thomas/nova-print/ 
      owner: thomas
  - name: Collectstatic
    become: yes
    become_user: thomas
    raw: cd ~thomas/nova-print/nova_print && python manage.py collectstatic --noinput
