- name: Deploy Django site
  hosts: nova-print
  remote_user: root
  tasks:
  - name: Upload nova_print django project sources
    synchronize:
      src: ~/code/nova-print/nova_print
      dest: ~thomas/nova-print/ 
      rsync_opts:
        - "--exclude=nova_print/db.sqlite3"
        - "--exclude=nova_print/static/js/frontend/node_modules"
  - name: pip install requirements
    become: yes
    become_user: thomas
    raw: pip install --user -r ~thomas/nova-print/nova_print/requirements.txt
  - name: python manage.py migrate
    raw: cd ~thomas/nova-print/nova_print && python manage.py migrate
    become: yes
    become_user: thomas
  - name: Collectstatic
    become: yes
    become_user: thomas
    raw: cd ~thomas/nova-print/nova_print && python manage.py collectstatic --noinput
