---
- name: Create user
  hosts: kaggle
  remote_user: root
  tasks:
  - name: Create apache group
    group:
      name: apache
      state: present
  - name: Add root to apache group
    user:
      name: root
      groups:
        - apache
        - sudo
      append: yes
  - name: Create user thomas
    user:
      name: thomas
      groups:
        - sudo
        - apache
  - name: Create .ssh folder
    file:
      path: ~thomas/.ssh
      state: directory
      owner: thomas
      group: thomas
      mode: 0700
  - name: Upload SSH key
    copy:
      src: authorized_keys
      dest: ~thomas/.ssh/authorized_keys
      owner: thomas
      group: thomas
      mode: 0700
  - name: Create .kaggle folder
    file:
      path: ~thomas/.kaggle
      state: directory
      owner: thomas
      group: thomas
      mode: 0700
  - name: Upload Kaggle API token
    copy:
      src: ~/.kaggle/kaggle.json
      dest: ~thomas/.kaggle/kaggle.json
      owner: thomas
      group: thomas
      mode: 0700
  - name: Install python deps
    apt:
      name:
        - python3-pip
        - python3-tk
      update_cache: yes
  - name: Install web servers deps
    apt:
      name:
        - apache2
  - name: Give apache group access to www
    file:
      name: /var/www/
      recurse: yes
      group: apache
      owner: root
      mode: 0775
  - name: Upload index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html
      owner: root
      group: apache
      mode: 0774
  - name: Upload httpd.conf
    copy:
      src: httpd.conf
      dest: /etc/apache2/httpd.conf
      owner: root
      group: apache
  - name: Create /var/www/img folder
    file:
      path: /var/www/img
      state: directory
      owner: thomas
      group: apache
      mode: 0774
  - name: Install system deps
    apt:
      name:
        - sudo
        - zip
        - unzip
        - git
- name: Install datascience tools
  hosts: kaggle
  tasks:
  - name: Install pip packages in user directory
    become: yes
    become_user: thomas
    pip:
      name:
        - numpy
        - scikit-learn
        - matplotlib
        - scipy
        - pandas
        - seaborn
        - ipython
        - kaggle
        - statsmodels
        - Pillow
        - requests
        - bs4
      extra_args: --user
      executable: pip3
